---
# Handlers for jenkins-jcasc role

- name: Reload JCasC
  ansible.builtin.uri:
    url: "http://localhost:{{ jenkins_port }}/configuration-as-code/reload"
    method: POST
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: true
    status_code: [200, 201]
  listen: "Reload JCasC"
  ignore_errors: true
