---
# Network tools installation

- name: Install network tool packages
  ansible.builtin.command: "{{ termux_bin }}/pkg install -y {{ item }}"
  loop: "{{ network_tool_packages }}"
  register: net_pkg_result
  changed_when: "'Setting up' in net_pkg_result.stdout"
  failed_when:
    - net_pkg_result.rc != 0
    - "'already installed' not in net_pkg_result.stdout"

- name: Verify OpenSSH installation
  ansible.builtin.command: "{{ termux_bin }}/ssh -V"
  register: ssh_version
  changed_when: false
  failed_when: false

- name: Display network tools installation summary
  ansible.builtin.debug:
    msg:
      - "Network tools installed:"
      - "{{ ssh_version.stderr if ssh_version.stderr else 'OpenSSH installed' }}"
      - "Total packages: {{ network_tool_packages | length }}"
