---
# System utilities installation

- name: Install system utility packages
  ansible.builtin.command: "{{ termux_bin }}/pkg install -y {{ system_utility_packages | join(' ') }}"
  register: sys_pkg_result
  changed_when: "'Setting up' in sys_pkg_result.stdout"

- name: Display system utilities installation summary
  ansible.builtin.debug:
    msg:
      - "System utilities installed:"
      - "  - htop (process monitor)"
      - "  - nano (text editor)"
      - "  - termux-services (service management)"
      - "  - runit (init system)"
      - "Total packages: {{ system_utility_packages | length }}"
