---
# Ansible inventory for Termux Jenkins setup
#
# IMPORTANT: Before running playbooks, update ansible_user with your device's user:
#   1. SSH into your Termux device: ssh -p 8022 <ip-address>
#   2. Run: whoami
#   3. Copy the output (e.g., "u0_a504") and set it as ansible_user below
#
# Note: Termux uses Android user IDs (format: u0_aN), NOT "termux"
#
# Usage:
#   ansible-playbook -i ansible/inventory/hosts.yaml playbook.yaml

all:
  children:
    termux:  # Parent group for all Termux hosts - inherits group_vars/termux.yaml
      children:
        termux_controller:
          hosts:
            phone1: &phone1_config
              ansible_host: 192.168.1.53  # Fresh install - CloudNord demo
              ansible_port: 8022
              ansible_user: u0_a557  # From whoami command
              ansible_connection: ssh
              ansible_ssh_private_key_file: ~/.ssh/termux_ed25519
              ansible_ssh_common_args: '-o IdentitiesOnly=yes'
              ansible_python_interpreter: /data/data/com.termux/files/usr/bin/python
              ansible_remote_tmp: /data/data/com.termux/files/home/.ansible/tmp

        termux_agents:
          hosts:
            phone1:  # First phone is both controller and agent
              <<: *phone1_config

            # Add more agents here:
            # phone2:
            #   ansible_host: 192.168.1.51
            #   ansible_port: 8022
            #   ansible_user: u0_a123  # Run 'whoami' on phone2 to get actual user
            # phone3:
            #   ansible_host: 192.168.1.52
            #   ansible_port: 8022
            #   ansible_user: u0_a456  # Run 'whoami' on phone3 to get actual user
