---
# Default variables for jenkins-jcasc role

# Termux paths
termux_prefix: /data/data/com.termux/files
termux_home: /data/data/com.termux/files/home
termux_usr: /data/data/com.termux/files/usr
termux_bin: /data/data/com.termux/files/usr/bin

# Jenkins paths
jenkins_home: "{{ termux_home }}/.jenkins"
jenkins_port: 8080

# JCasC configuration
jcasc_config_source: "{{ playbook_dir }}/../jcasc/jenkins.yaml"
jcasc_config_dest: "{{ jenkins_home }}/jenkins.yaml"
jcasc_reload_token: "{{ lookup('env', 'JCASC_RELOAD_TOKEN') | default('changeme-' + ansible_date_time.epoch, true) }}"

# Plugin management
plugins_file_source: "{{ playbook_dir }}/../jcasc/plugins.txt"
install_plugins_from_file: true

# Sample jobs
deploy_sample_jobs: true
jobs_source_dir: "{{ playbook_dir }}/../jcasc/jobs"

# Jenkins CLI
jenkins_cli_jar: "{{ jenkins_home }}/jenkins-cli.jar"
jenkins_cli_url: "http://localhost:{{ jenkins_port }}/jnlpJars/jenkins-cli.jar"

# Credentials
jenkins_admin_user: "{{ jenkins_admin_user | default('admin') }}"
jenkins_admin_password: "{{ jenkins_admin_password | default('admin') }}"

# Agent configuration (from jenkins-agent role)
agent_name: "{{ jenkins_agent_name | default('termux-agent-1') }}"
agent_home: "{{ jenkins_agent_home | default(termux_home + '/jenkins-agent') }}"
agent_labels: "{{ jenkins_agent_labels | default('android termux mobile') }}"
agent_ssh_key: "{{ jenkins_agent_ssh_key_path | default(jenkins_home + '/ssh') }}/{{ jenkins_agent_ssh_key_name | default('id_ed25519') }}"

# Reload configuration
reload_jcasc: true
verify_config: true

# Wait for configuration to apply
config_wait_timeout: 60
config_wait_delay: 5
jdk_tool_name: "OpenJDK-21"
