---
# Test playbook for termux-complete-setup role
# This playbook tests the complete package installation on an existing Termux device

- name: Test Termux Complete Setup Role
  hosts: termux_controller
  gather_facts: false
  become: false

  vars:
    # Enable all package groups for testing
    install_build_essentials: true
    install_languages: true
    install_dev_tools: true
    install_network_tools: true
    install_system_utilities: true
    install_termux_api: true

    # Adjust storage thresholds for testing on existing system
    minimum_storage_mb: 100
    recommended_storage_mb: 500

    # Enable verification
    verify_installations: true

    # Don't upgrade packages (save time)
    upgrade_packages_before_install: false

    # Skip termux-base role upgrades too
    update_packages: false
    upgrade_packages: false

  pre_tasks:
    - name: Display test information
      ansible.builtin.debug:
        msg:
          - "╔════════════════════════════════════════════════════════╗"
          - "║   Testing: termux-complete-setup Role                 ║"
          - "╚════════════════════════════════════════════════════════╝"
          - ""
          - "Target: {{ ansible_host }}:{{ ansible_port }}"
          - "User: {{ ansible_user }}"
          - ""
          - "This test will:"
          - "  1. Check available storage"
          - "  2. Install packages (skip if already installed)"
          - "  3. Verify tool installations"
          - ""

  roles:
    - role: ../roles/termux-complete-setup

  post_tasks:
    - name: Display test completion
      ansible.builtin.debug:
        msg:
          - ""
          - "╔════════════════════════════════════════════════════════╗"
          - "║   Test Complete!                                       ║"
          - "╚════════════════════════════════════════════════════════╝"
          - ""
          - "Check output above for:"
          - "  - Storage validation results"
          - "  - Package installation status"
          - "  - Tool verification results"
          - ""
