---
# Default variables for termux-buildtools role

# Termux paths
termux_prefix: /data/data/com.termux/files
termux_home: /data/data/com.termux/files/home
termux_usr: /data/data/com.termux/files/usr
termux_bin: /data/data/com.termux/files/usr/bin

# Build essentials
build_packages:
  - clang
  - make
  - cmake
  - pkg-config
  - binutils
  - autoconf
  - automake
  - libtool

# Language runtimes
language_runtimes:
  - python
  - nodejs
  - ruby
  - golang

# Version control
vcs_packages:
  - git
  - git-lfs

# Additional development tools
dev_tools:
  - jq
  - yq
  - zip
  - unzip
  - rsync

# Python packages
install_python_packages: true
python_pip_packages:
  # Note: 'pip' itself cannot be installed/upgraded via pip on Termux
  # It will break the python-pip package. Use 'pkg upgrade python-pip' instead.
  - setuptools
  - wheel
  - virtualenv
  - pytest

# Node.js packages
install_node_packages: true
node_global_packages:
  - npm
  - yarn

# Environment variables to set
env_vars:
  - { name: "EDITOR", value: "nano" }
  - { name: "VISUAL", value: "nano" }

# Profile configuration
configure_profile: true
profile_path: "{{ termux_home }}/.profile"

# Verify installations
verify_installations: true
