---
# Default variables for jenkins-controller role
# Note: Termux path variables (termux_prefix, termux_home, termux_usr, termux_bin),
# Jenkins paths (jenkins_home, jenkins_war, jenkins_port, java_bin), and jenkins_version
# are defined in group_vars/termux.yaml and inherited by all Termux hosts

# Jenkins WAR download
jenkins_war_url: "https://get.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war"
jenkins_war_path: "{{ jenkins_war }}"  # Uses centralized jenkins_war variable

# Jenkins directories
jenkins_log_dir: "{{ jenkins_home }}/logs"
jenkins_plugins_dir: "{{ jenkins_home }}/plugins"
jenkins_jobs_dir: "{{ jenkins_home }}/jobs"

# Jenkins configuration
jenkins_http_listen_address: "0.0.0.0"
jenkins_java_options: "-Djava.awt.headless=true -Xmx512m -Xms256m"
jenkins_args: "--httpPort={{ jenkins_port }} --httpListenAddress={{ jenkins_http_listen_address }}"

# Admin configuration
jenkins_admin_email: "admin@localhost"

# Service configuration
jenkins_service_enabled: true
jenkins_service_name: "jenkins"
jenkins_service_script: "{{ termux_home }}/bin/start-jenkins.sh"

# Plugin management
install_plugins: true
plugins_file: "{{ playbook_dir }}/../jcasc/plugins.txt"

# Skip setup wizard
skip_setup_wizard: true

# Wait for Jenkins to start
jenkins_wait_timeout: 300  # 5 minutes
jenkins_wait_delay: 10  # Check every 10 seconds

# Java configuration
# Note: In Termux, Java is installed directly to bin/, not /opt/openjdk
java_home: "{{ termux_usr }}"
openjdk_package_name: "openjdk-21"
